version: '3.1'

services:

  php73:
    build: 
      context: './php'
    volumes:
      - ../www:/var/www
    # environment:
    #   - APACHE_RUN_USER=1000
    #   - APACHE_RUN_GROUP=1000
    ports:
      - 8180:80
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=password
      - "TZ=Asia/Tokyo"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8888:80
    volumes:
      - ./pma/sessions:/sessions